### ISSUE TITLE
Update redmine from package install to docker install

### ISSUE THREAD

**Issue by qiaofeng1227** [Websoft9/ansible-redmine#5]

**Comment by qiaofeng1227** [comment]
Install way of redmine plugin ?

**Comment by chendelin1982** [comment]
```
version: '3.1'

services:

  redmine:
    image: redmine
    container_name: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
      REDMINE_SECRET_KEY_BASE: supersecretkey
      REDMINE_PLUGINS_MIGRATE: "true"
    volumes:
      - ./redmine_data:/usr/src/redmine/files
      - ./redmine-plugins:/usr/src/redmine/plugins
      - redmine-themes:/usr/src/redmine/public/themes

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
```
refer to: https://stackoverflow.com/questions/43424994/install-redmine-plug-in-using-docker-container
